#!/bin/bash 

# fastd Peers Check für die Freifunk Stuttgart GWs
# Frank Schiebel <frank@linuxmuster.net>
# GPLv3

# programs
STATUSPL="/etc/check_mk/ffs/status.pl"
FASTDSOCKET="/var/run/fastd-vpn00.sock"
JSONPARSE="/usr/bin/jq"
export LC_ALL=C
export LANG=C

[ -e /etc/default/ffs-check-fastdpeers ] && . /etc/default/ffs-check-fastdpeers

print_help() {
  usage: $0 [--fastdsocket=/var/run/fastd/fastd-vpn00.sock]
  cat <<EOF >&2
--help:		Dieser Text
--fastdsocket:	Socket zum betreffenden fastd
EOF
}
if [ "x" != "x$1" ]; then
TEMP=`getopt -o h --long help,fastdsocket: -- "$@"`
if [ $? != 0 ] ; then print_help >&2 ; exit 1 ; fi
eval set -- "$TEMP"
while true ; do
  case "$1" in
    --fastdsocket)	FASTDSOCKET="$2"; shift 2;;
    --help|-h)		print_help; exit 1;;
    --) shift ; break ;;
    *) echo "Unknown parameter $1, try -h" ; exit 1 ;;
  esac
done
fi

STATUSOUT=$($STATUSPL $FASTDSOCKET)
# Anzahl der Verbundenen Peers
namepeers=$(jq '.peers[] | if .address!="any" then .name else empty end' <<<$STATUSOUT)
numpeers=$(wc -w <<<$namepeers)
# Namen der verbundenen Peers
nameofgwpeers=$(xargs -n1 echo <<< $namepeers | grep '^gw[0-9]' | sort)
nameofnodepeers=$(xargs -n1 echo <<< $namepeers | grep -v '^gw[0-9]' | sort)
# Wieviele "normale" Nodes?
numnodepeers=$( wc -w <<< $nameofnodepeers )
# Wieviele Gateways?
numgwpeers=$( wc -w <<< $nameofgwpeers )

gwnames=""
for gwname in $nameofgwpeers; do
	gwnames="$gwnames $gwname"
done

nodenames=""
for nodename in $nameofnodepeers; do
	nodenames="$nodenames $nodename"
done

MSG="OK - $numpeers fastd-nodes connected, $numgwpeers GWs ($gwnames), $numnodepeers Nodes ($nodenames)"
SEP=""
EXITVALUE=0

if [ $numpeers -lt 3 ]; then 
	MSG="WARN - $numpeers fastd-nodes connected, $numgwpeers GWs ($gwnames), $numnodepeers Nodes"
	EXITVALUE=1
fi

if [ $numpeers -lt 1 ]; then 
	MSG="CRIT - $numpeers fastd-nodes connected, $numgwpeers GWs ($gwnames), $numnodepeers Nodes"
	EXITVALUE=2
fi
echo "$MSG | numpeers=$numpeers numgws=$numgwpeers numnodes=$numnodepeers"
exit $EXITVALUE

